version: '3.8'
services:
  hms-app:
    build: .
    ports:
      - "5000:5001"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=wagwan@2002
      - POSTGRES_DB=hotels
      # - DATABASE_URL: postgres://postgres:wagwan@2002@127.0.0.1:5432/hotels 
      - POSTGRES_HOST=127.0.0.1