version: '3.8'
services:
  hms-app-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules


  hms-app-backend:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    env_file:
      - ./.env
    
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=wagwan@2002
      - POSTGRES_DB=hotel
      # - DATABASE_URL: postgres://postgres:wagwan@2002@127.0.0.1:5432/hotels 
      - POSTGRES_HOST=127.0.0.1
  
  